#!/usr/bin/env bash
#
# Pass one or more filepaths as argument
#
# Every argument is checked for $pkg_pattern and
# all found packages are signed
#

sign_packages () {

	declare sign_as='dennistenhoove'
	declare pkg_pattern='*.pkg.tar.???'

	for f in $(find $args -name $pkg_pattern 2> /dev/null); do

		if [[ -e "$f.sig" ]]; then
			printf "$f is already signed, skipping...\n"
		else
			printf "Now signing $f as $sign_as\n"
			gpg --detach-sign --use-agent -u $sign_as --no-armor $f
		fi

	done

}

for args in "$@"; do
	sign_packages
done

